cp -p g:AzADChoose.png .
cp -p g:AzAddPlatform.png .
cp -p g:AzAddRedirect.png .
cp -p g:AzAppRegistrations.png .
cp -p g:AzButton.png .
cp -p g:AzClientSecret.png .
cp -p g:AzDelegatedPermissions.png .
cp -p g:AzFilter.png .
cp -p g:AzGrantAdminConsent.png .
cp -p g:AzGraphPermissions.png .
cp -p g:AzLogout.png .
cp -p g:AzNewApp.png .
cp -p g:AzNewRegistration.png .
cp -p g:AzPermissions.png .
cp -p g:AzRegister.png .
cp -p g:AzRequestPermission.png .
cp -p g:AzScope1.png .
cp -p g:AzScope2.png .
cp -p g:AzSearch.png .
cp -p g:AzSecret.png .
cp -p g:AzTestSecret.png .
